version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: always
    volumes:
      - storage_volume:/var/www/html/storage
      - uploads_volume:/var/www/html/public/uploads
      - ./:/var/www/html
    depends_on: []
    ports:
      - "8001:80"  # Coolify will handle routing

volumes:
  storage_volume:
  uploads_volume:
